//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrinGlobal.Search.Engine.AdminTool.GrinGlobalSearch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GrinGlobalSearch.ISearchHost")]
    public interface ISearchHost {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHost/Search", ReplyAction="http://tempuri.org/ISearchHost/SearchResponse")]
        System.Collections.Generic.List<int> Search(string searchString, bool ignoreCase, bool autoAndConsecutiveLiterals, System.Collections.Generic.List<string> indexNames, string resolverName, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHost/RotateIndexes", ReplyAction="http://tempuri.org/ISearchHost/RotateIndexesResponse")]
        void RotateIndexes(System.Collections.Generic.List<string> indexNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHost/GetLatestMessage", ReplyAction="http://tempuri.org/ISearchHost/GetLatestMessageResponse")]
        string GetLatestMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISearchHostChannel : GrinGlobal.Search.Engine.AdminTool.GrinGlobalSearch.ISearchHost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchHostClient : System.ServiceModel.ClientBase<GrinGlobal.Search.Engine.AdminTool.GrinGlobalSearch.ISearchHost>, GrinGlobal.Search.Engine.AdminTool.GrinGlobalSearch.ISearchHost {
        
        public SearchHostClient() {
        }
        
        public SearchHostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchHostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchHostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchHostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<int> Search(string searchString, bool ignoreCase, bool autoAndConsecutiveLiterals, System.Collections.Generic.List<string> indexNames, string resolverName, int offset, int limit) {
            return base.Channel.Search(searchString, ignoreCase, autoAndConsecutiveLiterals, indexNames, resolverName, offset, limit);
        }
        
        public void RotateIndexes(System.Collections.Generic.List<string> indexNames) {
            base.Channel.RotateIndexes(indexNames);
        }
        
        public string GetLatestMessage() {
            return base.Channel.GetLatestMessage();
        }
    }
}
