CREATE TABLE "MAIN"."SITE" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "FIELD1" NVARCHAR2(45) NULL
)
;
CREATE TABLE "PROD"."TEST1" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED
)
;
CREATE SEQUENCE PROD.TEST1_SQ;

            CREATE OR REPLACE TRIGGER PROD.TEST1_TR
            BEFORE INSERT ON "PROD"."TEST1"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.TEST1_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."FAM" (
    "FAMNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "VALIDFAMNO" NUMBER(11) NULL,
    "FAMILY" NVARCHAR2(25) NULL UNIQUE,
    "FAMAUTHOR" NVARCHAR2(100) NULL UNIQUE,
    "ALTFAMILY" NVARCHAR2(25) NULL,
    "SUBFAMILY" NVARCHAR2(25) NULL UNIQUE,
    "TRIBE" NVARCHAR2(25) NULL UNIQUE,
    "SUBTRIBE" NVARCHAR2(25) NULL UNIQUE,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
ALTER TABLE "PROD"."FAM" ADD CONSTRAINT validfamno_refs_famno_54ee6c7d FOREIGN KEY ("VALIDFAMNO") REFERENCES "PROD"."FAM" ("FAMNO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."CROP" (
    "CROPNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "CROP" NVARCHAR2(20) NULL UNIQUE,
    "CMT" NVARCHAR2(2000) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GN" (
    "GNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "VALIDGNO" NUMBER(11) NULL,
    "QUAL" NVARCHAR2(2) NULL,
    "GHYBRID" NVARCHAR2(1) NULL,
    "GENUS" NVARCHAR2(30) NULL UNIQUE,
    "GAUTHOR" NVARCHAR2(100) NULL UNIQUE,
    "SUBGENUS" NVARCHAR2(30) NULL UNIQUE,
    "SECTION" NVARCHAR2(30) NULL UNIQUE,
    "SERIES" NVARCHAR2(30) NULL UNIQUE,
    "SUBSERIES" NVARCHAR2(30) NULL UNIQUE,
    "FAMNO" NUMBER(11) NULL REFERENCES "PROD"."FAM" ("FAMNO") DEFERRABLE INITIALLY DEFERRED,
    "OTHFAMILY" NVARCHAR2(100) NULL,
    "CNAME" NVARCHAR2(30) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "SUBSECTION" NVARCHAR2(30) NULL UNIQUE
)
;
ALTER TABLE "PROD"."GN" ADD CONSTRAINT validgno_refs_gno_5afc285 FOREIGN KEY ("VALIDGNO") REFERENCES "PROD"."GN" ("GNO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."REG" (
    "REGNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "AREA" NVARCHAR2(20) NULL UNIQUE,
    "REGION" NVARCHAR2(30) NULL UNIQUE,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GEO" (
    "GEONO" NUMBER(11) NOT NULL PRIMARY KEY,
    "VALIDGEONO" NUMBER(11) NULL,
    "COUNTRY" NVARCHAR2(30) NULL UNIQUE,
    "STATE" NVARCHAR2(20) NULL UNIQUE,
    "ISOFULL" NVARCHAR2(100) NULL,
    "ISOSHORT" NVARCHAR2(60) NULL,
    "STATEFULL" NVARCHAR2(60) NULL,
    "ISO3" NVARCHAR2(3) NULL,
    "ISO2" NVARCHAR2(2) NULL,
    "ST" NVARCHAR2(3) NULL,
    "CFLAG" NVARCHAR2(1) NULL,
    "LATH" NVARCHAR2(1) NULL,
    "LONH" NVARCHAR2(1) NULL,
    "REGNO" NUMBER(11) NULL REFERENCES "PROD"."REG" ("REGNO") DEFERRABLE INITIALLY DEFERRED,
    "CHANGED" DATE NULL,
    "OLDNAME" NVARCHAR2(100) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
ALTER TABLE "PROD"."GEO" ADD CONSTRAINT validgeono_refs_geono_447defb9 FOREIGN KEY ("VALIDGEONO") REFERENCES "PROD"."GEO" ("GEONO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."COOP" (
    "CNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "VALIDCNO" NUMBER(11) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "LNAME" NVARCHAR2(40) NULL,
    "TITLE" NVARCHAR2(5) NULL,
    "FNAME" NVARCHAR2(30) NULL,
    "JOB" NVARCHAR2(40) NULL,
    "ORG" NVARCHAR2(60) NULL,
    "ORGID" NVARCHAR2(10) NULL,
    "ADD1" NVARCHAR2(60) NULL UNIQUE,
    "ADD2" NVARCHAR2(60) NULL,
    "ADD3" NVARCHAR2(60) NULL,
    "CITY" NVARCHAR2(20) NULL UNIQUE,
    "ZIP" NVARCHAR2(10) NULL,
    "GEONO" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."GEO" ("GEONO") DEFERRABLE INITIALLY DEFERRED,
    "PHONE1" NVARCHAR2(30) NULL,
    "PHONE2" NVARCHAR2(30) NULL,
    "FAX" NVARCHAR2(30) NULL,
    "EMAIL" NVARCHAR2(100) NULL,
    "ACTIVE" NVARCHAR2(1) NULL,
    "CAT" NVARCHAR2(4) NULL,
    "ARSREGION" NVARCHAR2(3) NULL,
    "DISCIPLINE" NVARCHAR2(10) NULL,
    "INITIALS" NVARCHAR2(6) NULL,
    "COOP" NVARCHAR2(100) NULL UNIQUE,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
ALTER TABLE "PROD"."COOP" ADD CONSTRAINT validcno_refs_cno_44815465 FOREIGN KEY ("VALIDCNO") REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."TAX" (
    "TAXNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "VALIDTAXNO" NUMBER(11) NULL,
    "SHYBRID" NVARCHAR2(1) NULL,
    "SPECIES" NVARCHAR2(30) NULL,
    "SAUTHOR" NVARCHAR2(100) NULL,
    "SSPHYBRID" NVARCHAR2(1) NULL,
    "SUBSP" NVARCHAR2(30) NULL,
    "SSPAUTHOR" NVARCHAR2(100) NULL,
    "VARHYBRID" NVARCHAR2(1) NULL,
    "VAR" NVARCHAR2(30) NULL,
    "VARAUTHOR" NVARCHAR2(100) NULL,
    "SVHYBRID" NVARCHAR2(1) NULL,
    "SUBVAR" NVARCHAR2(30) NULL,
    "SVAUTHOR" NVARCHAR2(100) NULL,
    "FHYBRID" NVARCHAR2(1) NULL,
    "FORMA" NVARCHAR2(30) NULL,
    "FAUTHOR" NVARCHAR2(100) NULL,
    "GNO" NUMBER(11) NOT NULL REFERENCES "PROD"."GN" ("GNO") DEFERRABLE INITIALLY DEFERRED,
    "CROPNO" NUMBER(11) NULL REFERENCES "PROD"."CROP" ("CROPNO") DEFERRABLE INITIALLY DEFERRED,
    "PSITE1" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "PSITE2" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "REST" NVARCHAR2(10) NULL,
    "LIFEFORM" NVARCHAR2(10) NULL,
    "FERT" NVARCHAR2(10) NULL,
    "PENDING" NVARCHAR2(1) NULL,
    "QUAL" NVARCHAR2(6) NULL,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "VERIFIED" DATE NULL,
    "TAXON" NVARCHAR2(100) NULL UNIQUE,
    "TAXAUTHOR" NVARCHAR2(100) NULL UNIQUE,
    "PROTOLOGUE" NVARCHAR2(240) NULL,
    "TAXCMT" NVARCHAR2(2000) NULL,
    "SITECMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "OTHNAME" NVARCHAR2(240) NULL
)
;
ALTER TABLE "PROD"."TAX" ADD CONSTRAINT validtaxno_refs_taxno_30642f77 FOREIGN KEY ("VALIDTAXNO") REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."TAXTORC" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "TAXNO" NUMBER(11) NOT NULL,
    "DNO" NUMBER(11) NOT NULL,
    "CT" NUMBER(11) NULL,
    "TAXON" NVARCHAR2(70) NULL,
    "CROP" NVARCHAR2(20) NULL,
    "CROPNO" NUMBER(11) NULL,
    "GENUS" NVARCHAR2(30) NULL
)
;
CREATE SEQUENCE PROD.TAXTORC_SQ;

            CREATE OR REPLACE TRIGGER PROD.TAXTORC_TR
            BEFORE INSERT ON "PROD"."TAXTORC"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.TAXTORC_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."PI" (
    "PIVOL" NUMBER(11) NOT NULL PRIMARY KEY,
    "PIYEAR" NUMBER(11) NOT NULL,
    "LOWPI" NUMBER(11) NOT NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."ACC" (
    "ACID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACP" NVARCHAR2(4) NULL UNIQUE,
    "ACNO" NUMBER(11) NOT NULL UNIQUE,
    "ACS" NVARCHAR2(4) NULL UNIQUE,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "WHYNULL" NVARCHAR2(10) NULL,
    "CORE" NVARCHAR2(1) NULL,
    "BACKUP" NVARCHAR2(1) NULL,
    "LIFEFORM" NVARCHAR2(10) NULL,
    "ACIMPT" NVARCHAR2(10) NULL,
    "UNIFORM" NVARCHAR2(10) NULL,
    "ACFORM" NVARCHAR2(2) NULL,
    "RECEIVED" DATE NOT NULL,
    "DATEFMT" NVARCHAR2(10) NULL,
    "TAXNO" NUMBER(11) NOT NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "PIVOL" NUMBER(11) NULL REFERENCES "PROD"."PI" ("PIVOL") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."EVAL" (
    "ENO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ENAME" NVARCHAR2(100) NULL UNIQUE,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "GEONO" NUMBER(11) NULL REFERENCES "PROD"."GEO" ("GEONO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "METHODS" NVARCHAR2(4000) NULL,
    "STUDYTYPE" NVARCHAR2(10) NULL
)
;
CREATE TABLE "PROD"."AACT" (
    "AACTNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACTION" NVARCHAR2(10) NULL,
    "OCCURRED" DATE NULL,
    "FMTOCCURRED" NVARCHAR2(10) NULL,
    "COMPLETED" DATE NULL,
    "FMTCOMPLETED" NVARCHAR2(10) NULL,
    "SHOWWEB" NVARCHAR2(1) NULL,
    "NARR" NVARCHAR2(2000) NULL,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NULL REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NOT NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."LIT" (
    "ABBR" NVARCHAR2(20) NULL PRIMARY KEY,
    "STDABBR" NVARCHAR2(240) NULL,
    "REFTITLE" NVARCHAR2(240) NULL,
    "EDITOR" NVARCHAR2(240) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."ACIT" (
    "CITNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "ABBR" NVARCHAR2(20) NULL REFERENCES "PROD"."LIT" ("ABBR") DEFERRABLE INITIALLY DEFERRED,
    "CITTITLE" NVARCHAR2(240) NULL,
    "AUTHOR" NVARCHAR2(240) NULL,
    "CITYR" NUMBER(11) NULL,
    "CITREF" NVARCHAR2(60) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."AG" (
    "AGNAME" NVARCHAR2(20) NULL PRIMARY KEY,
    "CMT" NVARCHAR2(240) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "URL" NVARCHAR2(240) NULL
)
;
CREATE TABLE "PROD"."IM" (
    "IMNAME" NVARCHAR2(20) NULL PRIMARY KEY,
    "SITE" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "IVT" NVARCHAR2(2) NULL,
    "MUNITS" NVARCHAR2(2) NULL,
    "DEBIT" NVARCHAR2(1) NULL,
    "DFORM" NVARCHAR2(2) NULL,
    "DQUANT" NUMBER(11) NULL,
    "DUNITS" NVARCHAR2(2) NULL,
    "DCRITICAL" NUMBER(11) NULL,
    "RCRITICAL" NUMBER(11) NULL,
    "REGEN" NVARCHAR2(10) NULL,
    "PTESTS" NUMBER(11) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "CNO" NUMBER(11) NULL
)
;
CREATE TABLE "PROD"."IV" (
    "IVID" NUMBER(11) NOT NULL PRIMARY KEY,
    "IVP" NVARCHAR2(4) NULL UNIQUE,
    "IVNO" NUMBER(11) NOT NULL UNIQUE,
    "IVS" NVARCHAR2(8) NULL UNIQUE,
    "IVT" NVARCHAR2(2) NULL UNIQUE,
    "IMNAME" NVARCHAR2(20) NULL REFERENCES "PROD"."IM" ("IMNAME") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "DISTRIBUTE" NVARCHAR2(1) NULL,
    "LOC1" NVARCHAR2(10) NULL,
    "LOC2" NVARCHAR2(10) NULL,
    "LOC3" NVARCHAR2(10) NULL,
    "LOC4" NVARCHAR2(10) NULL,
    "ONHAND" NUMBER(11) NULL,
    "MUNITS" NVARCHAR2(2) NULL,
    "DEBIT" NVARCHAR2(1) NULL,
    "DFORM" NVARCHAR2(2) NULL,
    "DQUANT" NUMBER(11) NULL,
    "DUNITS" NVARCHAR2(2) NULL,
    "DCRITICAL" NUMBER(11) NULL,
    "RCRITICAL" NUMBER(11) NULL,
    "PSTATUS" NVARCHAR2(10) NULL,
    "STATUS" NVARCHAR2(10) NULL,
    "STATCMT" NVARCHAR2(60) NULL,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "PARENT" NUMBER(11) NULL,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "BACKUPIV" NUMBER(11) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."ORD" (
    "ORNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ORIGNO" NUMBER(11) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "LOCALNO" NUMBER(11) NULL,
    "ORTYPE" NVARCHAR2(2) NULL,
    "ORDERED" DATE NULL,
    "STATUS" NVARCHAR2(10) NULL,
    "DONE" NVARCHAR2(1) NULL,
    "ACTED" DATE NULL,
    "SOURCE" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "ORDERER" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "SHIPTO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "FINAL" NUMBER(11) NOT NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "REQREF" NVARCHAR2(10) NULL,
    "SUPPLYLOW" NVARCHAR2(1) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "REQUEST" NVARCHAR2(900) NULL
)
;
ALTER TABLE "PROD"."ORD" ADD CONSTRAINT origno_refs_orno_244ff12b FOREIGN KEY ("ORIGNO") REFERENCES "PROD"."ORD" ("ORNO") DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE "PROD"."AL" (
    "ALNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACTION" NVARCHAR2(10) NULL UNIQUE,
    "ACTED" DATE NOT NULL UNIQUE,
    "ACID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "IVID" NUMBER(11) NULL REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "ORNO" NUMBER(11) NULL REFERENCES "PROD"."ORD" ("ORNO") DEFERRABLE INITIALLY DEFERRED,
    "OLDTAXNO" NUMBER(11) NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "NEWTAXNO" NUMBER(11) NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."AN" (
    "ANNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "IDTYPE" NVARCHAR2(10) NULL,
    "IDRANK" NUMBER(11) NULL,
    "TOPNAME" NVARCHAR2(1) NULL,
    "PLANTID" NVARCHAR2(40) NULL UNIQUE,
    "SEARCHID" NVARCHAR2(40) NULL,
    "AGNAME" NVARCHAR2(20) NULL UNIQUE REFERENCES "PROD"."AG" ("AGNAME") DEFERRABLE INITIALLY DEFERRED,
    "IVID" NUMBER(11) NULL REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."BAD" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "IVID" NUMBER(11) NULL
)
;
CREATE SEQUENCE PROD.BAD_SQ;

            CREATE OR REPLACE TRIGGER PROD.BAD_TR
            BEFORE INSERT ON "PROD"."BAD"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.BAD_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."DSC" (
    "DNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "DQNAME" NVARCHAR2(10) NULL UNIQUE,
    "DNAME" NVARCHAR2(30) NULL,
    "CAC" NVARCHAR2(1) NULL,
    "DCAT" NVARCHAR2(10) NULL,
    "OBTYPE" NVARCHAR2(10) NULL,
    "USECODE" NVARCHAR2(1) NULL,
    "OBMAXLEN" NUMBER(11) NULL,
    "OBFORMAT" NVARCHAR2(15) NULL,
    "OBMAX" NUMBER(11) NULL,
    "OBMIN" NUMBER(11) NULL,
    "ORGTYPE" NVARCHAR2(10) NULL,
    "ORGFORMAT" NVARCHAR2(15) NULL,
    "CROPNO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."CROP" ("CROPNO") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "DEF" NVARCHAR2(240) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."CD" (
    "DNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."DSC" ("DNO") DEFERRABLE INITIALLY DEFERRED,
    "CODE" NVARCHAR2(30) NULL PRIMARY KEY,
    "DEF" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."CG" (
    "CGID" NVARCHAR2(20) NULL PRIMARY KEY,
    "CGNAME" NVARCHAR2(60) NULL UNIQUE,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "HISTORICAL" NVARCHAR2(1) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."CN" (
    "TAXNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "CNAME" NVARCHAR2(50) NULL PRIMARY KEY,
    "SOURCE" NVARCHAR2(20) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "CNID" NVARCHAR2(50) NULL
)
;
CREATE TABLE "PROD"."DEL_LOG" (
    "DEL_ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "OWNER_TABLE" NVARCHAR2(30) NULL,
    "TABLE_COL" NVARCHAR2(400) NULL,
    "TABLE_VAL" NVARCHAR2(2000) NULL,
    "SITE" NVARCHAR2(8) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "DATE_STAMP" DATE NULL
)
;
CREATE TABLE "PROD"."DIST" (
    "DISTNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "TAXNO" NUMBER(11) NOT NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "GEONO" NUMBER(11) NULL REFERENCES "PROD"."GEO" ("GEONO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."DURL" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "URLTYPE" NVARCHAR2(10) NULL UNIQUE,
    "SEQNO" NUMBER(11) NOT NULL UNIQUE,
    "CROPNO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."CROP" ("CROPNO") DEFERRABLE INITIALLY DEFERRED,
    "DNO" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."DSC" ("DNO") DEFERRABLE INITIALLY DEFERRED,
    "CODE" NVARCHAR2(30) NULL UNIQUE REFERENCES "PROD"."CD" ("CODE") DEFERRABLE INITIALLY DEFERRED,
    "CAPTION" NVARCHAR2(60) NULL,
    "URL" NVARCHAR2(100) NULL,
    "SITE" NUMBER(11) NOT NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NOT NULL,
    "MODIFIED" DATE NULL,
    "ENO" NUMBER(11) NULL
)
;
CREATE SEQUENCE PROD.DURL_SQ;

            CREATE OR REPLACE TRIGGER PROD.DURL_TR
            BEFORE INSERT ON "PROD"."DURL"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.DURL_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."ECIT" (
    "CITNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ENO" NUMBER(11) NOT NULL REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "ABBR" NVARCHAR2(20) NULL REFERENCES "PROD"."LIT" ("ABBR") DEFERRABLE INITIALLY DEFERRED,
    "CITTITLE" NVARCHAR2(240) NULL,
    "AUTHOR" NVARCHAR2(240) NULL,
    "CITYR" NUMBER(11) NULL,
    "CITREF" NVARCHAR2(240) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."EMBR" (
    "CNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."MRK" (
    "MRKNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "CROPNO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."CROP" ("CROPNO") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NUMBER(11) NOT NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "MARKER" NVARCHAR2(100) NULL UNIQUE,
    "SYNONYMS" NVARCHAR2(200) NULL,
    "REPEAT_MOTIF" NVARCHAR2(100) NULL,
    "PRIMERS" NVARCHAR2(200) NULL,
    "ASSAY_CONDITIONS" NVARCHAR2(4000) NULL,
    "RANGE_PRODUCTS" NVARCHAR2(60) NULL,
    "KNOWN_STANDARDS" NVARCHAR2(300) NULL,
    "GENBANK_NO" NVARCHAR2(20) NULL,
    "MAP_LOCATION" NVARCHAR2(100) NULL,
    "POSITION" NVARCHAR2(1000) NULL,
    "CMT" NVARCHAR2(4000) NULL,
    "POLY_TYPE" NVARCHAR2(10) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GA" (
    "GANO" NUMBER(11) NOT NULL PRIMARY KEY,
    "MRKNO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."MRK" ("MRKNO") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "METHOD" NVARCHAR2(2000) NULL,
    "SCORING_METHOD" NVARCHAR2(1000) NULL,
    "CONTROL_VALUES" NVARCHAR2(1000) NULL,
    "NO_OBS_ALLELES" NUMBER(11) NULL,
    "MAX_GOB_ALLELES" NUMBER(11) NULL,
    "SIZE_ALLELES" NVARCHAR2(100) NULL,
    "UNUSUAL_ALLELES" NVARCHAR2(100) NULL,
    "CMT" NVARCHAR2(4000) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GCIT" (
    "CITNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "GNO" NUMBER(11) NOT NULL REFERENCES "PROD"."GN" ("GNO") DEFERRABLE INITIALLY DEFERRED,
    "ABBR" NVARCHAR2(20) NULL REFERENCES "PROD"."LIT" ("ABBR") DEFERRABLE INITIALLY DEFERRED,
    "CITTITLE" NVARCHAR2(240) NULL,
    "AUTHOR" NVARCHAR2(240) NULL,
    "CITYR" NUMBER(11) NULL,
    "CITREF" NVARCHAR2(60) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GENERAL_CONFIG" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "CONFIG" NVARCHAR2(1024) NULL,
    "LABEL" NVARCHAR2(64) NULL,
    "USERID" NVARCHAR2(32) NULL
)
;
CREATE SEQUENCE PROD.GENERAL_CONFIG_SQ;

            CREATE OR REPLACE TRIGGER PROD.GENERAL_CONFIG_TR
            BEFORE INSERT ON "PROD"."GENERAL_CONFIG"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.GENERAL_CONFIG_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."GERMRULE" (
    "RULENO" NUMBER(11) NOT NULL PRIMARY KEY,
    "SUBSTRATA" NVARCHAR2(70) NULL,
    "TEMP" NVARCHAR2(30) NULL,
    "REQUIREMENTS" NVARCHAR2(500) NULL,
    "AUTHOR" NVARCHAR2(20) NULL,
    "CATEGORY" NVARCHAR2(10) NULL,
    "DAYS" NVARCHAR2(20) NULL,
    "TAXNO" NUMBER(11) NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GNT" (
    "GNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."GN" ("GNO") DEFERRABLE INITIALLY DEFERRED,
    "FAMNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."FAM" ("FAMNO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GOB" (
    "GOBNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "GANO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."GA" ("GANO") DEFERRABLE INITIALLY DEFERRED,
    "IVID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "INDIV" NUMBER(11) NULL UNIQUE,
    "GOB" NVARCHAR2(1000) NULL,
    "GENBANK_LINK" NVARCHAR2(200) NULL,
    "IMAGE_LINK" NVARCHAR2(200) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."GRINWIN_INI" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "TYPE" NVARCHAR2(32) NULL,
    "LABEL" NVARCHAR2(32) NULL,
    "VALUE" NVARCHAR2(64) NULL
)
;
CREATE SEQUENCE PROD.GRINWIN_INI_SQ;

            CREATE OR REPLACE TRIGGER PROD.GRINWIN_INI_TR
            BEFORE INSERT ON "PROD"."GRINWIN_INI"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.GRINWIN_INI_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."SRC" (
    "SRCNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "SRCTYPE" NVARCHAR2(10) NULL,
    "SRCDATE" DATE NULL,
    "DATEFMT" NVARCHAR2(10) NULL,
    "ORIGIN" NVARCHAR2(1) NULL,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "GEONO" NUMBER(11) NULL REFERENCES "PROD"."GEO" ("GEONO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "SRCQUAL" NVARCHAR2(10) NULL
)
;
CREATE TABLE "PROD"."HAB" (
    "SRCNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."SRC" ("SRCNO") DEFERRABLE INITIALLY DEFERRED,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "LATD" NUMBER(11) NULL,
    "LATM" NUMBER(11) NULL,
    "LATS" NUMBER(11) NULL,
    "LATH" NVARCHAR2(1) NULL,
    "LOND" NUMBER(11) NULL,
    "LONM" NUMBER(11) NULL,
    "LONS" NUMBER(11) NULL,
    "LONH" NVARCHAR2(1) NULL,
    "ELEV" NUMBER(11) NULL,
    "QUANT" NUMBER(11) NULL,
    "UNITS" NVARCHAR2(2) NULL,
    "CFORM" NVARCHAR2(2) NULL,
    "PLANTS" NUMBER(11) NULL,
    "LOCALITY" NVARCHAR2(240) NULL,
    "HABITAT" NVARCHAR2(240) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "GCTYPE" NVARCHAR2(10) NULL,
    "GSTYPE" NVARCHAR2(10) NULL
)
;
CREATE TABLE "PROD"."IACT" (
    "IACTNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACTION" NVARCHAR2(10) NULL,
    "OCCURRED" DATE NULL,
    "DATEFMT" NVARCHAR2(10) NULL,
    "QUANT" NUMBER(11) NULL,
    "UNITS" NVARCHAR2(2) NULL,
    "IFORM" NVARCHAR2(2) NULL,
    "IVID" NUMBER(11) NOT NULL REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NULL REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "IACTQUAL" NVARCHAR2(10) NULL
)
;
CREATE TABLE "PROD"."IG" (
    "IGNAME" NVARCHAR2(100) NULL PRIMARY KEY,
    "SITE" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."IGM" (
    "IVID" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "IGNAME" NVARCHAR2(100) NOT NULL PRIMARY KEY REFERENCES "PROD"."IG" ("IGNAME") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NVARCHAR2(100) NOT NULL PRIMARY KEY REFERENCES "PROD"."IG" ("IGNAME") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."IPR" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "IPRTYPE" NVARCHAR2(10) NULL UNIQUE,
    "IPRID" NVARCHAR2(40) NULL UNIQUE,
    "IPRNO" NUMBER(11) NULL,
    "IPRCROP" NVARCHAR2(60) NULL,
    "IPRNAME" NVARCHAR2(240) NULL,
    "ISSUED" DATE NULL,
    "EXPIRED" DATE NULL,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "CITNO" NUMBER(11) NULL REFERENCES "PROD"."ACIT" ("CITNO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "ACCEPTED" DATE NULL,
    "EXPECTED" DATE NULL
)
;
CREATE SEQUENCE PROD.IPR_SQ;

            CREATE OR REPLACE TRIGGER PROD.IPR_TR
            BEFORE INSERT ON "PROD"."IPR"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.IPR_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."MBR" (
    "CNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "CGID" NVARCHAR2(20) NOT NULL PRIMARY KEY REFERENCES "PROD"."CG" ("CGID") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "LOCALID" NVARCHAR2(10) NULL
)
;
CREATE TABLE "PROD"."MCIT" (
    "CITNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "MRKNO" NUMBER(11) NOT NULL REFERENCES "PROD"."MRK" ("MRKNO") DEFERRABLE INITIALLY DEFERRED,
    "ABBR" NVARCHAR2(20) NULL REFERENCES "PROD"."LIT" ("ABBR") DEFERRABLE INITIALLY DEFERRED,
    "CITTITLE" NVARCHAR2(240) NULL,
    "AUTHOR" NVARCHAR2(240) NULL,
    "CITYR" NUMBER(11) NULL,
    "CITREF" NVARCHAR2(60) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."MENU_ITEM" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "MENU_ID" NUMBER(11) NULL,
    "SEQNO" NUMBER(11) NULL,
    "TYPE" NVARCHAR2(32) NULL,
    "MODULE" NVARCHAR2(64) NULL,
    "PATH" NVARCHAR2(64) NULL,
    "ITEM" NVARCHAR2(64) NULL,
    "HINT" NVARCHAR2(64) NULL,
    "ARG" NVARCHAR2(254) NULL
)
;
CREATE SEQUENCE PROD.MENU_ITEM_SQ;

            CREATE OR REPLACE TRIGGER PROD.MENU_ITEM_TR
            BEFORE INSERT ON "PROD"."MENU_ITEM"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.MENU_ITEM_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."MENU_NAME" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "MENU_ID" NUMBER(11) NULL,
    "MENU_NAME" NVARCHAR2(32) NULL,
    "USER_ID" NVARCHAR2(32) NULL,
    "PARENT" NVARCHAR2(32) NULL,
    "TITLE" NVARCHAR2(64) NULL
)
;
CREATE SEQUENCE PROD.MENU_NAME_SQ;

            CREATE OR REPLACE TRIGGER PROD.MENU_NAME_TR
            BEFORE INSERT ON "PROD"."MENU_NAME"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.MENU_NAME_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."NARR" (
    "ACID" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "NTYPE" NVARCHAR2(1) NULL PRIMARY KEY,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "NARR" NVARCHAR2(4000) NULL
)
;
CREATE TABLE "PROD"."OACT" (
    "OACTNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "ACTION" NVARCHAR2(10) NULL,
    "ACTED" DATE NOT NULL,
    "ACTID" NVARCHAR2(40) NULL,
    "ORNO" NUMBER(11) NOT NULL REFERENCES "PROD"."ORD" ("ORNO") DEFERRABLE INITIALLY DEFERRED,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "COOP" NVARCHAR2(100) NULL,
    "CNO" NUMBER(11) NULL
)
;
CREATE TABLE "PROD"."QUAL" (
    "QNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "QUAL" NVARCHAR2(30) NULL,
    "DNO" NUMBER(11) NOT NULL REFERENCES "PROD"."DSC" ("DNO") DEFERRABLE INITIALLY DEFERRED,
    "DEF" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."OB" (
    "DNO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."DSC" ("DNO") DEFERRABLE INITIALLY DEFERRED,
    "OB" NVARCHAR2(30) NULL UNIQUE,
    "ACID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "QNO" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."QUAL" ("QNO") DEFERRABLE INITIALLY DEFERRED,
    "IVID" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "ORGVALUE" NVARCHAR2(30) NULL,
    "FREQ" DOUBLE PRECISION NULL,
    "MEAN" NUMBER(11) NULL,
    "HIGH" NUMBER(11) NULL,
    "LOW" NUMBER(11) NULL,
    "SDEV" NUMBER(11) NULL,
    "SSIZE" NUMBER(11) NULL,
    "CMT" NVARCHAR2(500) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "OBNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "RANK" NUMBER(11) NULL
)
;
CREATE TABLE "PROD"."OI" (
    "ORNO" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."ORD" ("ORNO") DEFERRABLE INITIALLY DEFERRED,
    "OINO" NUMBER(11) NULL UNIQUE,
    "ITEM" NVARCHAR2(40) NULL,
    "QUANT" NUMBER(11) NULL,
    "UNITS" NVARCHAR2(2) NULL,
    "DFORM" NVARCHAR2(2) NULL,
    "REST" NVARCHAR2(10) NULL,
    "STATUS" NVARCHAR2(10) NULL,
    "ACTED" DATE NULL,
    "CNO" NUMBER(11) NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "IVID" NUMBER(11) NULL REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "ACID" NUMBER(11) NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "TAXNO" NUMBER(11) NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "TAXON" NVARCHAR2(100) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "ITNO" NUMBER(11) NOT NULL PRIMARY KEY
)
;
CREATE TABLE "PROD"."PED" (
    "ACID" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "RELEASED" DATE NULL,
    "DATEFMT" NVARCHAR2(10) NULL,
    "CITNO" NUMBER(11) NULL REFERENCES "PROD"."ACIT" ("CITNO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "PEDIGREE" NVARCHAR2(2000) NULL
)
;
CREATE TABLE "PROD"."PT" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "IVID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "PTTYPE" NVARCHAR2(10) NULL UNIQUE,
    "PTCODE" NVARCHAR2(10) NULL UNIQUE,
    "BEGAN" DATE NULL,
    "FINISHED" DATE NULL UNIQUE,
    "RESULTS" NVARCHAR2(10) NULL,
    "NEEDED" NUMBER(11) NULL,
    "STARTED" NUMBER(11) NULL,
    "COMPLETED" NUMBER(11) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE SEQUENCE PROD.PT_SQ;

            CREATE OR REPLACE TRIGGER PROD.PT_TR
            BEFORE INSERT ON "PROD"."PT"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.PT_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."QUAR" (
    "ACID" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "QTYPE" NVARCHAR2(10) NULL PRIMARY KEY,
    "STATUS" NVARCHAR2(10) NULL,
    "CNO" NUMBER(11) NOT NULL REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "ENTERED" DATE NULL,
    "ESTABLISH" DATE NULL,
    "EXPECTED" DATE NULL,
    "RELEASED" DATE NULL,
    "CMT" NVARCHAR2(240) NULL,
    "SITE" NUMBER(11) NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."SEC_PRIV" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "SEC_ROLE_ID" NUMBER(11) NULL,
    "SEC_USER_ID" NUMBER(11) NULL,
    "TABLE_NAME" NVARCHAR2(50) NULL,
    "TARGET_SEC_USER_ID" NUMBER(11) NULL,
    "PRIV_CREATE" NVARCHAR2(1) NULL,
    "PRIV_READ" NVARCHAR2(1) NULL,
    "PRIV_UPDATE" NVARCHAR2(1) NULL,
    "PRIV_DELETE" NVARCHAR2(1) NULL,
    "ENABLED" NVARCHAR2(1) NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NULL
)
;
CREATE TABLE "PROD"."SEC_ROLE" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ROLE_NAME" NVARCHAR2(50) NULL
)
;
CREATE TABLE "PROD"."SEC_USER" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "USER_NAME" NVARCHAR2(50) NULL UNIQUE,
    "PASSWORD" NVARCHAR2(255) NULL,
    "ENABLED" NVARCHAR2(1) NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP NULL
)
;
CREATE TABLE "PROD"."SEC_USER_ROLE" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "SEC_USER_ID" NUMBER(11) NOT NULL,
    "SEC_ROLE_ID" NUMBER(11) NOT NULL
)
;
CREATE TABLE "PROD"."SMBR" (
    "SRCNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."SRC" ("SRCNO") DEFERRABLE INITIALLY DEFERRED,
    "ACID" NUMBER(11) NOT NULL REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."SQL_OPERATORS" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "OPER" NVARCHAR2(12) NULL,
    "SEQNO" NUMBER(11) NULL
)
;
CREATE SEQUENCE PROD.SQL_OPERATORS_SQ;

            CREATE OR REPLACE TRIGGER PROD.SQL_OPERATORS_TR
            BEFORE INSERT ON "PROD"."SQL_OPERATORS"
            FOR EACH ROW
            WHEN (new."ID" IS NULL)
                BEGIN
                    SELECT PROD.SQL_OPERATORS_SQ.nextval
                    INTO :new."ID" FROM dual;
                END;
                /
CREATE TABLE "PROD"."TAUT" (
    "SHORTAUT" NVARCHAR2(30) NULL PRIMARY KEY,
    "LONGAUT" NVARCHAR2(100) NULL,
    "SMARKAUT" NVARCHAR2(30) NULL,
    "LMARKAUT" NVARCHAR2(100) NULL,
    "SHEXPAUT" NVARCHAR2(30) NULL,
    "LGEXPAUT" NVARCHAR2(100) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NOT NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."TCIT" (
    "CITNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "TAXNO" NUMBER(11) NOT NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "ABBR" NVARCHAR2(20) NULL REFERENCES "PROD"."LIT" ("ABBR") DEFERRABLE INITIALLY DEFERRED,
    "CITTITLE" NVARCHAR2(240) NULL,
    "AUTHOR" NVARCHAR2(240) NULL,
    "CITYR" NUMBER(11) NULL,
    "CITREF" NVARCHAR2(60) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."TURL" (
    "TURLNO" NUMBER(11) NOT NULL PRIMARY KEY,
    "URLTYPE" NVARCHAR2(10) NULL,
    "FAMNO" NUMBER(11) NOT NULL REFERENCES "PROD"."FAM" ("FAMNO") DEFERRABLE INITIALLY DEFERRED,
    "GNO" NUMBER(11) NULL REFERENCES "PROD"."GN" ("GNO") DEFERRABLE INITIALLY DEFERRED,
    "TAXNO" NUMBER(11) NULL REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "CAPTION" NVARCHAR2(240) NULL,
    "URL" NVARCHAR2(100) NULL,
    "SITE" NUMBER(11) NOT NULL REFERENCES "MAIN"."SITE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NOT NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."USES" (
    "TAXNO" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "PROD"."TAX" ("TAXNO") DEFERRABLE INITIALLY DEFERRED,
    "TAXUSE" NVARCHAR2(10) NULL PRIMARY KEY,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "USETYPE" NVARCHAR2(250) NULL
)
;
CREATE TABLE "PROD"."VIA" (
    "VIANO" NUMBER(11) NOT NULL PRIMARY KEY,
    "TESTED" DATE NOT NULL,
    "DATEFMT" NVARCHAR2(10) NULL,
    "NORM" NUMBER(11) NULL,
    "ABNORM" NUMBER(11) NULL,
    "DORMANT" NUMBER(11) NULL,
    "VIABLE" NUMBER(11) NULL,
    "VIGOR" NVARCHAR2(10) NULL,
    "SAMPLE" NUMBER(11) NULL,
    "REPS" NUMBER(11) NULL,
    "IVID" NUMBER(11) NOT NULL REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "ENO" NUMBER(11) NULL REFERENCES "PROD"."EVAL" ("ENO") DEFERRABLE INITIALLY DEFERRED,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL
)
;
CREATE TABLE "PROD"."VOU" (
    "ACID" NUMBER(11) NOT NULL UNIQUE REFERENCES "PROD"."ACC" ("ACID") DEFERRABLE INITIALLY DEFERRED,
    "VTYPE" NVARCHAR2(10) NULL UNIQUE,
    "IVID" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."IV" ("IVID") DEFERRABLE INITIALLY DEFERRED,
    "CNO" NUMBER(11) NULL UNIQUE REFERENCES "PROD"."COOP" ("CNO") DEFERRABLE INITIALLY DEFERRED,
    "VOUCHERED" DATE NULL UNIQUE,
    "DATEFMT" NVARCHAR2(10) NULL,
    "COLLID" NVARCHAR2(40) NULL UNIQUE,
    "VLOC" NVARCHAR2(500) NULL UNIQUE,
    "VCONTENT" NVARCHAR2(100) NULL,
    "CMT" NVARCHAR2(240) NULL,
    "USERID" NVARCHAR2(10) NULL,
    "CREATED" DATE NULL,
    "MODIFIED" DATE NULL,
    "THUMBNAIL" NVARCHAR2(500) NULL,
    "VNO" NUMBER(11) NOT NULL PRIMARY KEY
)
;
COMMIT;
