CREATE USER GRINGLOBAL IDENTIFIED BY temppass DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp
/

GRANT unlimited tablespace TO GRINGLOBAL
/

GRANT connect, resource TO GRINGLOBAL
/

GRANT CREATE Session TO GRINGLOBAL
/

EXIT;